body:
  type     : String
  unique   : false
  required: [true, Title is required.]
  validations:
    - validator: isLength
      arguments: [3, 500]
      message: Title should be between {ARGS[0]} and {ARGS[1]} characters
created:
  type: Date
  default: Date.now
from:
  type: Id
  ref: User
post:
  type: Id
  ref: Post
