title:
  type  : String
  unique: false
  trim: true
  required: [true, Title is required.]
  validations:
    - validator: isLength
      arguments: [3, 120]
      message: Title should be between {ARGS[0]} and {ARGS[1]} characters
body:
  type  : String
  unique: false
  trim: true
  required: [true, Post body is required.]
  validations:
    - validator: isLength
      arguments: [10, 100000]
      message: Post body should be between {ARGS[0]} and {ARGS[1]} characters
slug:
  type: String
  required: true
  select: false
author:
  type: Id
  ref: User
edited:
  type: Date
  default: Date.now
created:
  type: Date
  default: Date.now
state:
  type: [String]
  enum: 'Object.keys(C.POST_STATES)'
  default: [C.POST_STATES.DRAFT]
  select: false
liked:
  type: [Id]
  default: []
  ref: Post
comments:
  type: [Id]
  default: []
  ref: Comment
